site:
  title: Documentation (with Kapa)
  url: http:localhost:5000
  start_page: hz-flow::index.adoc
  robots: disallow
  keys:
    docsearch_id: 'QK2EAH8GB0'
    docsearch_api: 'ef7bd9485eafbd75d6e8425949eda1f5'
    docsearch_index: 'prod_hazelcast_docs'
    ai_search_id: 'ad664bf0-07e2-42e7-9150-2e1b04b15cca'    
content:
  sources: 
  - url: .
    branches: HEAD
    start_path: docs
ui: 
  bundle:
    url:  ../hazelcast-docs-ui/build/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
    # Download images from kroki at build time (does not work for inline images)
    # kroki-fetch-diagram: true
    # Inlude next and previous links on each page
    page-pagination: true@
    idprefix: ''
    # Separate anchor link names by dashes
    idseparator: '-'
    # Variables used in the docs
    page-survey: https://www.surveymonkey.co.uk/r/NYGJNF9
  extensions:
    - ./docs-tabs-library/tabs-block.js
    # - asciidoctor-kroki
