= Load Balancer 
:description: Load Balancer setup 

When deploying multiple {short-product-name} Servers, they can be deployed behind a Load Balancer to scale out the system.  https://traefik.io/traefik[Traefik] is used as an example in this section, although any other  Load Balancer can be used (e.g. nginx).

== When is a Load Balancer Required?

A Load Balancer, or Reverse Proxy is required when deploying multiple Flow instances (for example in a production deployment of 3 Flow instances).  It will distribute the load from incoming requests across each Flow instance.

== Transport Layer Security (TLS)

TLS (also known as HTTPS or SSL) can be used to secure the connection between clients and Flow Servers in production.  If you use HTTPS for your front-end listener on the load balancer, you need to configure a TLS certificate on the load balancer.   

You can create a certificate using a tool like OpenSSL or use a cloud service such as Let’s Encrypt or AWS Certificate Manager.  When creating a certificate to use with the load balancer, the domain name must be specified.    

A fully qualified domain name (FQDN) must be specified for the certificate, for example flow.example.com An asterisk can be be used as a wildcard in the left-most position of the domain (for example *.flow.example.com)


== Web Sockets
The *WebSocket API* enables a two-way interactive communication session between the user's browser (or API consumer) and a server. With this API, you can send messages to a server and receive event-driven responses without having to poll the server for a reply.  Web sockets typically use a long-lived persistent connection.

Flow uses Web Sockets in a number of areas : between the UI and the Flow Server, and also optionally when publishing an endpoint as a Websocket endpoint.  The UI performs a periodic heartbeat on the websocket connection to keep the connection open. 

It’s important that the Load Balancer is configured to expose the HTTP headers required to Upgrade the HTTP connection to a Web socket connection.

For traefik it’s done like this:

----
labels:
      - "traefik.http.routers.hazelcast-flow.middlewares=sslheader-proto,sslheader-port"
      - "traefik.http.middlewares.sslheader-proto.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.sslheader-port.headers.customrequestheaders.X-Forwarded-Port=443"
----

== Listener

The Load Balancer Listener configuration is how UI browsers and API consumers will access Flow.  A listener checks for connection requests using the configured protocol and port, for example TCP Port 443.  The default action and any additional rules that you create determine how the Application Load Balancer routes requests to its registered targets.  The Listener configuration also includes the details of the TLS certificate to use.

== Target Group

Target Groups define a service exposed by the Load Balancer, for Flow a target group will contain all of the Flow Service instances.  For traefik the example traefik configuration to Load balance across the Flow Server TCP Endpoints on TCP Port 9021 looks like:


----
  - "traefik.enable=true"
  - "traefik.http.routers.hazelcast-flow.rule=Host(`flow.example.com`)"
  - "traefik.http.routers.hazelcast-flow.entrypoints=web"
  - "traefik.http.services.hazelcast-flow.loadbalancer.server.port=9021"
----


== Cross-Origin Resource Sharing (CORS)

CORS is a mechanism where a web page can specify which resources from a different server or domain can be loaded by the browser.  Cross-origin requests are blocked by default and CORS defines a way for a browser and web service to determine when it’s safe to allow a cross-origin request.

When Single Sign On (SSO) between Flow and Management Center is enabled and Management Center is deployed on a different domain from Flow, it’s important that CORS configuration is applied to Management Center.

Management Center has the system property `hazelcast.mc.flow.address` which when configured, is added to the CORS Access-Control-Allow-Origin HTTP Response header from Management Center.  If Management Center is configured as an Identity Provider for Flow, Flow will try to fetch some resources from Management Center when loading the Flow UI main page.  This CORS configuration enables that cross-domain communication. 

