= Deploying {short-product-name}
:description: How to deploy {short-product-name} to production

Our recommended deployment method is with `docker compose` or deploying the Docker container directly using the orchestrator of your choice.

== Deploying using Docker Compose

A sample `docker-compose.yml` file is maintained on https://github.com/hazelcast/hazelcast-flow-docker-compose[Github]

With examples for:

* Running with an external Hazelcast cluster
* Using external IDP config
* Configuring to include metrics

Note that, by default, {short-product-name} does not enable
authentication or role-based authorization, and you'll need to enable these.

== Production concepts

When deploying to production, there are common tasks you may wish to perform:

* Enable xref:deploying:authentication.adoc[authentication] and xref:deploying:authorization.adoc[authorization] in {short-product-name}
* Use a xref:workspace:overview.adoc#reading-workspace-conf-from-git[Git-backed workspace.conf file], to align with IAC
* Understand how xref:deploying:managing-secrets.adoc[secrets are handled] in {short-product-name}
* Understand how to configure {short-product-name} via xref:deploying:configuring.adoc#docker[application properties] or xref:deploying:configuring.adoc#passing-{short-product-name}-application-configuration[environment variables]

== Further deployment templates

These further templates provide code samples for provisioning infrastructure and deploying into orchestration platforms

=== Deploying with Terraform

{short-product-name} maintains example deployment scripts for production configurations of {short-product-name} in Terraform.
These are available on https://github.com/hazelcast/hazelcast-flow-terraform[Github]
