= Deploying {short-product-name}
:description: How to deploy {short-product-name} to production

Our recommended deployment method is with `docker compose` or deploying the Docker container directly using the orchestrator of your choice.

== Production concepts

When deploying to production, there are common tasks you may wish to perform:

* Enable xref:deploying:authentication.adoc[authentication] and xref:deploying:authorization.adoc[authorization] in {short-product-name}
* Use a xref:workspace:overview.adoc#reading-workspace-conf-from-git[Git-backed workspace.conf file], to align with IAC
* Understand how xref:deploying:managing-secrets.adoc[secrets are handled] in {short-product-name}
* Understand how to configure {short-product-name} via xref:deploying:configuring.adoc#docker[application properties] or xref:deploying:configuring.adoc#passing-{short-product-name}-application-configuration[environment variables]

== Deploying using Docker Compose

A sample `docker-compose.yml` is maintained by the {short-product-name} team and published at https://start.{code-product-name}.com[start.{code-product-name}.com]. 
#Author's note - link broken - please confirm#

It contains reasonable defaults for getting a local environment running.  Note that, by default, {short-product-name} does not enable
authentication or role-based authorization, and you'll need to enable these.


== Further deployment templates

These further templates provide code samples for provisioning infrastructure and deploying into orchestration platforms:

=== Deploying with Terraform

A sample `docker-compose.yml` is maintained by the {short-product-name} team and published at https://start.{code-product-name}.com[start.{code-product-name}.com]. 
#Author's note - link broken - please confirm. Also, this seems a repetition of the above - is this intended or has something gone wrong with the merge?#

It contains reasonable defaults for getting a local environment running.  Note that, by default, {short-product-name} does not enable
authentication or role-based authorization, and you'll need to enable these.

{short-product-name} maintains example deployment scripts for production configurations of {short-product-name} in Terraform.

// These are available https://github.com/{short-product-name}api/deploy[here].

== Networking between components

{short-product-name} is packaged as a collection of container images which need to be able to communicate with one another.

The addresses used are configured in a file, which by default is loaded from  `config/services.conf`.

The location of the config file can be set by passing `--vyne.services.config-file` in the command line when starting {short-product-name}.

|===
| Config setting | Default value

| `vyne.services.config-file`
| `config/services.conf`
|===

If the config file doesn't exist, then a default file with reasonable defaults is written on startup.

An example of the config file is shown below:

[,hocon]
----
services {
    analytics-server {
        url="http://vyne-analytics-server"
    }
    flow-server {
        url="http://flow"
        rsocket-port=7655
    }
}
----

The following table outlines the components and the default network addresses and ports that are
expected to be exposed.  If deploying in a network like Docker Swarm or Kubernetes, it is expected
that services are available on the configured addresses.

#Author's note - links in table are broken - please confirm what these should be:#

|===
| Component & Image | Default network address | Port(s)

| https://hub.docker.com/r/{code-product-name}/{short-product-name}[{short-product-name} Server] +
*Required* +
(UI and Query execution)
| http://{short-product-name}
| 80

| https://hub.docker.com/r/{code-product-name}/analytics-server[Analytics server] +
*Optional* +
(Stores query history and lineage, as well as pipeline logs)
| http://{short-product-name}-analytics-server
| 80 (http) +
7654 (RSocket)

| https://hub.docker/com/r/{code-product-name}/stream-server[Stream server] +
*Optional* +
Executes long-lived data streams
| http://stream-server
|
|===

NOTE: When {short-product-name} is configured to distribute work across a cluster, ports must also be exposed to enable multicasting. See xref:distributing-work-on-a-cluster.adoc[Distributing work across a cluster] for more information.
