= CSV
:description: Working with CSV data in {short-product-name}

To declare that a type should be read/written as CSV, add the `com.{code-product-name}.formats.Csv` annotation to a model:

[,taxi]
----
import flow.formats.Csv

@Csv
model Person {
  firstName : FirstName inherits String
}
----

== CSV options

The following options are available:

|===
| Parameter name | Description | Default value

| delimiter
| The delimiter between records
| `,`

| firstRecordAsHeader
| Indicates if the first record should be read as a header
| true

| nullValue
| Specify a custom string to be read as `null`
|

| containsTrailingDelimiters
| Indicates if each row contains a delimiter which should be ignored
| false

| quoteChar
| Specifies which character should be read as a quoting character
| `"`
|===

For example:

[,taxi]
----
import flow.formats.Csv

@Csv(
  delimiter = "|",
  nullValue = "NULL"
)
model Person {
  firstName : String
  lastName : String
  age : Int
}
----

////

== Using column() references

WARNING: Using the `by column` tag is deprecated. Field names in the model are now used to match columns.

It's possible (but discouraged) to use `by column("")` references to declare a column:

[,taxi]
----
model Person {
  firstName : FirstName by column("fName")
}
----

////