= Data formats in {short-product-name}
:description: Learn about specifying data formats in {short-product-name}

Data formats specify how {short-product-name} should read and write data.

By default, {short-product-name} assumes that data is provided as JSON. However, by adding a data format to a model, this
can be modified to any type of serialization format.

== API specs and message formats

Some API specs which define transport also have their own message format (e.g., Protobuf).  If that's the
case, you generally don't need to do anything - {short-product-name} applies the correct formats when parsing the API spec.

|===
| API Spec | Message Format | Docs

| Protobuf
| Protobuf
| xref:protobuf.adoc[Protobuf docs]

| OpenAPI
| JSON
| xref:describe-data-sources:open-api.adoc[OpenAPI docs]

| SOAP
| XML
| xref:describe-data-sources:soap.adoc[SOAP docs]

| Avro
| Avro           
| xref:data-formats:avro.adoc[Avro docs]
|===

== Use message formats in Taxi

If you're using Taxi to describe your API specs, you need to specify the data format that is used for reading/writing messages.

By default, messages are expected to be in JSON.  Other formats can be specified using an annotation on the top level type.

For example:

[,taxi]
----
import flow.formats.Xml

@Xml
model Person {
  firstName: FirstName
}
----

You only need to apply the annotation to the top level entity.

|===
| Message format | Annotation | Links

| Json
| Not needed - default format
| -

| Xml
| `flow.formats.Xml`
| xref:data-formats:xml.adoc[Xml annotation docs]

| Csv
| `flow.formats.Csv`
| xref:data-formats:csv.adoc[Csv annotation docs]

| Protobuf
| Not supported in Taxi - Use a Protobuf spec
| xref:data-formats:protobuf.adoc[Protobuf]

| Avro
| Not supported directly in Taxi - Use an Avro spec
| xref:data-formats:avro.adoc[Avro]
|===
