= 5.5.0 Release Notes
:description Release notes for 5.5.0

These release notes list any new features, enhancements, fixes and breaking changes that were included in the initial version of {long-product-name}.

== Overview

{long-product-name} is a next-generation data integration gateway that automates the discovery, integration and transformation of data. Build fast, robust, trackable, and adaptable data integrations that self-repair and adapt when schemas change.

== Key Components

=== Dashboard
Landing page with insights into the health of your project’s connections, overview of the schema changes, and metrics of the currently running services.

=== Query Editor
Multi-tab UI to run ad-hoc TaxiQL queries, preview results and track lineage. Visually explore the data sources being queried and joined to retrieve your results.

=== Workspaces
Organize and group your schemas, API specs, data source information and describe your data and the capabilities they provide. These descriptions are used to generate integration on the fly, and power your catalog.

=== Data Catalog
Explore the data you hold and navigate the relationships and fields available within it. Visually discover your data models and schemas.

=== Publish Queries
Queries can be exposed as streaming queries over HTTP (using Server-Sent Events) or Websocket (or both). Saved queries are executed in background by {short-product-name} as Hazelcast Jet jobs.

=== Infrastructure as Code support
Set up your schemas and data models through a convenient UI interface, then deploy the generated schemas into your production environment using Git operations

== Next Steps

To get started:

* Read our xref:introduction:quickstart.adoc[]
* Look over our xref:guides:index.adoc[]
* Learn how to xref:query:write-queries.adoc[]

//TODO: update with public marketing pages when available