= Glossary
:description: Glossary of {short-product-name} terms, acronyms and abbreviations 

For a full list of the terms, acronyms and abbreviations used in our documentation, see the: https://docs.hazelcast.com/hazelcast/latest/glossary[Hazelcast glossary].

[glossary]
BFF:: Backend-for-frontend.
CLI:: Command-line interface. 
Data pipeline:: A series of actions that ingest data from one or more sources and move it to a destination for storage and analysis.

Data source:: The databases, APIs, and messages that fuel Hazelcast Flow. 
Hazelcast Flow:: Flow is a data gateway that automates the integration of microservices across your enterprise. Flow accelerates application development by connecting multiple data sources and APIs together, without having to write integration code.
IaC:: Infrastructure as Code.
JWT:: JSON Web Token, an open standard for transmitting information securely between parties as a JSON object.
K8s:: Kubernetes (often abbreviated to K8s), an open-source system that manages and deploys containerized applications.
mTLS:: Mutual authentication (mTLS), a method that ensures the authenticity of the parties at each end of a network connection.
Mutation:: Mutation queries make changes; for example, in performing a task or updating a record.
OIDC:: OpenID Connect provider.
OOME:: Out of Memory Error.
PKCE:: Proof Key for Code Exchange, an extension used in OAuth 2.0 to improve security for public clients.
Projection:: Projections are a way of taking data from one place, and then transforming and combining it with other data sources.
Query:: A request built using Flow's ability to retrieve and analyze data from different sources across an ecosystem. For example, a query might stitch three services together: a database, API and Kafka streaming data.
SAML:: Security Assertion Markup Language identity provider (IdP) authenticates users and passes authentication data to a service provider. 
Semantic data type:: A method of encoding data that allows software to discover and map data based upon its meaning rather than its structure.
Serialization:: Process of converting an object into a stream of bytes in order to store it or transmit it to memory, a database, or a file. Its main purpose is to save the state of an object so it can be recreated when needed. The reverse process is called deserialization.
SSE:: Server-sent events.
TaxiQL:: Taxi is a simple query language for describing how data and APIs across an ecosystem relate to one another.
Taxonomy:: The practice of classifying and categorizing data. 
Time to live (TTL):: A value that determines how long data is retained, before it is discarded from Flow's internal cache.
Workspace:: A Flow Workspace is a collection of schemas, API specs and Taxi projects that describe data sources and provide a description of the data and capabilities they provide.
WSDL:: Web Services Description Language.