= Quickstart
:description: 'Connect all your APIs & data sources dynamically, without writing integration code'

{long-product-name} automates integration for your microservices.

Get started right now, by spinning up {short-product-name} on your machine

[,bash]
----
curl https://start.{code-product-name}.com > docker-compose.yml
docker compose up -d
----

Then visit http://localhost:9022 in your browser.

== What is {long-product-name}?

{short-product-name} is a data gateway that automates the integration, transformation and discovery of data from data sources (API's, databases, message brokers) across your enterprise.

{short-product-name} integrates on-the-fly, automatically adjusting as your data sources change.

This is powered by rich semantic schemas, which infer how data across your organisation links together, and automate the integration and discovery of data.

<ImageWithCaption src=\{NetworkDiagram} addLightBackground/>

== Quick Links

Once you have {short-product-name} running locally, connect your microservices, and start querying for data+++<QuickLinks>++++++<QuickLink title="Connecting data sources" icon="connect" href="docs/describing-data-sources/configuring-connections" description="Connect your APIs, Databases and Message Queues to {short-product-name}.">++++++</QuickLink>+++ +++<QuickLink title="Querying" icon="query" href="/docs/querying/writing-queries" description="Query for data through {short-product-name}'s API, and let {short-product-name} handle the integration plumbing for you.">++++++</QuickLink>+++ +++<QuickLink title="Follow a guide" icon="guides" href="/docs/guides" description="A handful of guides to help get productive with {short-product-name}">++++++</QuickLink>+++ +++<QuickLink title="Head to production" icon="production" href="/docs/deploying/production-deployments" description="Deploy {short-product-name} on your Kubernetes cluster or using Docker Compose">++++++</QuickLink>++++++</QuickLinks>+++

== Getting help

Stuck?  Need help?  Have an idea?  We'd love to hear from your.

You can connect with the {short-product-name} team in a number of ways

* https://github.com/{short-product-name}api/{short-product-name}/issues[Submit an issue] on our Github repo
* https://github.com/{short-product-name}api/{short-product-name}/discussions[Start a discussion] over at Github
* https://join.slack.com/t/{short-product-name}api/shared_invite/zt-697laanr-DHGXXak5slqsY9DqwrkzHg[Chat to the team] on Slack
* We're https://twitter.com/{short-product-name}api[@{short-product-name}api] on Twitter
