= Performing mutations
:description: Triggering updates / mutations using TaxiQL

Mutation queries make changes somewhere i.e., in performing a task, or updating a record.

Mutating operations are defined in Taxi using the `write` modifier:

[,taxi]
----
service FlightsService {
  write operation bookFlight(BookingRequest):BookingConfirmation
  write operation sendFlightManifest(Manifest):ManifestConfirmation
}
----

Mutating operations are excluded from being invoked during a query (i.e., anything with a `find {}` or `stream {}` directive.)

Instead, they are invoked using a `call` directive.

[,taxi]
----
find { Passengers[] }
call FlightsService::sendFlightManifest
----

In this example, a list of `Passengers` is fetched, and converted into a `Manifest` to call the `sendFlightManifest` operation
of the `FlightsService`.

Many different data sources support mutations, such as xref:describing-data-sources:databases.adoc#writing-data-to-a-database[databases],
xref:describing-data-sources:kafka.adoc#writing-to-a-kafka-topic[Kafka], xref:describing-data-sources:mongodb.adoc#writing-data-to-a-collection[MongoDB],
and xref:describing-data-sources:hazelcast.adoc#writing-data-to-hazelcast[Hazelcast].

Consult the docs for the relevant data source to learn more.
