= Configuring connections

The `connections.conf` file defines connections for systems that {short-product-name} understands how to connect to.

A connection is required for most - but not all - data sources (eg., Databases, AWS services, etc.).  HTTP connections (OpenAPI / SOAP, etc) are generally self-descriptive
enough not to require additional metadata.

== Declaring in your Taxi project

Connections are defined in a `connections.conf`, which lives inside a Taxi project within your link:/docs/workspace/overview[workspace].

Inside your `taxi.conf` file in your project, declare where you're keeping your config for {short-product-name}.

By convention, this lives at `{code-product-name}/config/connections.conf`, but this is configurable.

```hocon taxi.conf
  name: com.myproject/demo
  version: 0.1.0
  sourceRoot: src/

____
additionalSources: {
     "@{code-product-name}/config" : "{code-product-name}/config/*.conf" +
 }
```
____

Your connections config file is a HOCON file, specifying how to connect to various resources.

For example:

```hocon connections.conf
jdbc {
  orders {
    connectionName = orders
    connectionParameters {
      database = ordersdb
      host = localhost
      username = martypitt
      password = $\{superSecretPassword}
      port = 5432

 }
 jdbcDriver = POSTGRES   } } ```

////
## Choosing between UI vs Config file
All connections can be configured through the UI, using the connection editor and schema editor - this is often
the easiest way to get started.   All connections are stored within the config file, including those configured in the UI.

However, when you're scripting your deployment, or want reproducible environments, it's often preferable to have
configuration that can be checked into version control or scripted.

In those situations, configuring connections via the config file directly is the way to go.
////

== Passing sensitive data

It may not always be desirable to specify sensitive connection information directly in the config file, especially
if these are being checked into source control.

Environment variables can be used anywhere in the config file, following the https://github.com/lightbend/config#uses-of-substitutions[HOCON standards].

For example:

```hocon connections.conf
jdbc {
   another-connection {
      connectionName = another-connection
      jdbcDriver = POSTGRES
      connectionParameters {
         // .. other params omitted for bevity ..
         password = $\{postgres_password} // Reads the environment variable "postgres_password"
      }
   }
}

----

<Callout type="note" title="See also...">
  Also check out <a href='/docs/deploying/managing-secrets'>Managing Secrets</a> to see how to securely manage sensitive information in your connections
</Callout>



### Correctly handling substitutions in URLs
Substitution of variable inside a URL using HOCON can be tricky.

In short, here's how substitutions need to be defined:

```hocon
query-server {
   // The Url has specifal characters (:), so needs to be inside of quotes.
   // However, variable substitution doesn't work inside of quotes,
   // so the variable must be outside of quotes.
   url="http://"${MY_VARIABLE}":9305"
}
----

For more information, see https://github.com/lightbend/config/issues/633[this issue] in the HOCON library

== Database connections

Database connections are defined under the `jdbc` element within the `connections.conf` file.

[,hocon]
----
jdbc { // The root element for database connections
   another-connection { // Defines a connection called "another-connection"
      connectionName = another-connection // The name of the connection.  Must match the key used above.
      jdbcDriver = POSTGRES // Defines the driver to use.  See below for the possible options
      connectionParameters { // A list of connection parameters.  The actual values here are defined by the driver selected.
         database = transactions // The name of the database
         host = our-db-server // The host of the database
         password = super-secret // The password
         port = "2003" // The port
         username = jack // The username to connect with
      }
   }
}
----

=== Supported drivers

=== Postgres

To configure a Postgres connection, specify `jdbcDriver = POSTGRES`

Connection parameters are as follows:

|===
| Parameter name | Description

| `host`
| The host address of the Postgres database

| `port`
| The port to connect to. Defaults to  `5432`

| `database`
| The name of the database on the Postgres server

| `username`
| Optional. The username to use when connecting

| `password`
| Optional. The password to use when connecting
|===

==== Example

[,HOCON]
----
jdbc { // The root element for database connections
   another-connection { // Defines a connection called "another-connection"
      connectionName = another-connection // The name of the connection.  Must match the key used above.
      jdbcDriver = POSTGRES // Defines the driver to use.  See below for the possible options
      connectionParameters { // A list of connection parameters.  The actual values here are defined by the driver selected.
         database = transactions // The name of the database
         host = our-db-server // The host of the database
         password = super-secret // The password
         port = "2003" // The port
         username = jack // The username to connect with
      }
   }
}
----

=== MySQL

To configure a MySql connection, specify `jdbcDriver = MYSQL`

Connection parameters are as follows:

|===
| Parameter name | Description

| `host`
| The host address of the MySQL database

| `port`
| The port to connect to. Defaults to  `3306`

| `database`
| The name of the database on the MySql server

| `username`
| Optional. The username to use when connecting

| `password`
| Optional. The password to use when connecting
|===

==== Example

[,HOCON]
----
jdbc {
    mysql-docker {
        connectionName=mysql-docker
        connectionParameters {
            database=test
            host=localhost
            password=my-secret-pw
            port="3306"
            username=root
        }
        jdbcDriver=MYSQL
    }
}
----

=== MSSQL Server

To configure a Postgres connection, specify `jdbcDriver = MSSQL`

Connection parameters are as follows:

| Parameter name           | Description                                                                                             |
|------------------|----------------------------------------------------------------------|
| `host`                   | The host address of the MSSQL database                                                                  |
| `port`                   | The port to connect to. Defaults to  `1443`                                                             |
| `database`               | The name of the database on the MS SQL server                                                           |
| `username`               | Optional. The username to use when connecting                                                           |
| `password`               | Optional. The password to use when connecting                                                           |
| `schema`                 | Optional. The schema to use - defaults to `dbo`                                                         |
| `trustServerCertificate` | Optional. Forces {short-product-name} to trust the certificate that's provided by the SQL Server. Defaults to `true` |
| `encrypt`                | Optional. Defines if the connection to MSSQL server should be encrypted. Defaults to `true`             |

==== Example

[,HOCON]
----
jdbc {
    sqlServerConnection {
        connectionName=sqlServerConnection
        connectionParameters {
            database=Northwind
            encrypt="true"
            host=localhost
            password=ChangeMe
            port="14330"
            schema=dbo
            trustServerCertificate="true"
            username=sa
        }
        jdbcDriver=MSSQL
    }
}
----

=== Redshift

To configure a Postgres connection, specify `jdbcDriver = REDSHIFT`

Connection parameters are as follows:

|===
| Parameter name | Description

| `host`
| The host address of the Redshift database

| `port`
| The port to connect to. Defaults to  `5439`

| `database`
| The name of the database on the Redshift server

| `username`
| Optional. The username to use when connecting

| `password`
| Optional. The password to use when connecting
|===

==== Example

[,HOCON]
----
jdbc { // The root element for database connections
   another-connection { // Defines a connection called "another-connection"
      connectionName = another-connection // The name of the connection.  Must match the key used above.
      jdbcDriver = REDSHIFT // Defines the driver to use.  See below for the possible options
      connectionParameters { // A list of connection parameters.  The actual values here are defined by the driver selected.
         database = transactions // The name of the database
         host = our-db-server // The host of the database
         password = super-secret // The password
         port = "2003" // The port
         username = jack // The username to connect with
      }
   }
}
----

=== Snowflake

To configure a Postgres connection, specify `jdbcDriver = SNOWFLAKE`

Connection parameters are as follows:

|===
| Parameter name | Description

| `account`
| The name of the Snowflake account

| `schema`
| The name of the schema to connect to

| `db`
| The name of the database to connect to

| `warehouse`
| The name of the warehouse where the snowflake db exists

| `username`
| The username to use when connecting

| `password`
| The password to use when connecting

| `role`
| The role to specify when connecting
|===

==== Example

[,HOCON]
----
jdbc { // The root element for database connections
   another-connection { // Defines a connection called "another-connection"
      connectionName = another-connection // The name of the connection.  Must match the key used above.
      jdbcDriver = SNOWFLAKE // Defines the driver to use.  See below for the possible options
      connectionParameters { // A list of connection parameters.  The actual values here are defined by the driver selected.
        account = mySnowflakeAccount123.eu-west-1
        schema = public
        db = demo_db
        warehouse = COMPUTE_WH
        schema = public
        role = QUERY_RUNNER
      }
   }
}
----

== Kafka connections

Read about defining Kafka connections in the dedicated documentation for link:/docs/describing-data-sources/kafka#defining-a-connection-to-your-kafka-broker[Kafka].

== AWS connections

AWS connections are stored under the `aws` element.

{short-product-name} uses AWS connections, for example, to connect to SQS for data pipelines and other services as part of query execution.

{short-product-name} will use the https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default[AWS default credentials provider] by default. This means you can configure the access credentials and region with environment variables (`AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` & `AWS_DEFAULT_REGION`). When running {short-product-name} in AWS (e.g. ECS), it'll also automatically pick up the role used to run the service and use that.

You can also configure the AWS connections manually which can be useful in cases where you need to connect to various different AWS accounts from a single installation of {short-product-name}. As with any other config file value, you can either set the value explicitly, or read from an environment variable (as shown).

aws {
    my-aws-account {
        connectionName=my-aws-account
        // Optional Parameter. When not provided {short-product-name} will use the https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default[AWS default credentials provider] by default.
        accessKey=${?AWS_ACCESS_KEY_ID}
        // Optional Parameter. When not provided {short-product-name} will use the https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default[AWS default credentials provider] by default.
        secretKey=${?AWS_SECRET_ACCESS_KEY}
        // Mandatory
        region=$\{AWS_REGION}
        // Optional parameter for development and testing purposes to point to a different endpoint such as a LocalStack installation.
        endPointOverride=${?AWS_ENDPOINT_OVERRIDE}
    }
}
```

== Mongo connections

Read about defining Mongo connections in the dedicated documentation for link:/docs/describing-data-sources/mongodb#defining-a-connection-to-your-mongo-database[Mongo].

=== Testing with Localstack

You can point {short-product-name} at an AWS mock running on https://localstack.cloud/[Localstack] by specifying the `endPointOverride` property
in the connection.
