= Enable role-based authorization
:description: Configure {short-product-name} authorization

NOTE: To use role-based authorization, you must have configured authentication with Management Center (MC). xref:authentication.adoc[Learn how to do this].

{short-product-name} uses role-based authorization to control which users can perform which tasks.

[#flow-roles]
== {short-product-name} roles

Roles are used to grant <<permissions,permissions>> to users, which allow users to perform different actions on the {short-product-name} platform.

////
Internal note to Hazelcast employees:

Roles cannot be configured on the MC side, but they can be configured in Flow. Flow comes with a reasonable set of default roles, but we can choose to create our own.
For the first release, we chose to use the default Flow roles.

If the file is not present on startup, a new file is created the first time a user logs in.
Roles are configured in a config file, typically found at `config/roles.conf`.

Example role configuration in Flow:
[,hocon]
----
// Defines roles, and assigns them authorities.
// Users who are granted these roles will be authorized to perform
// the related activities.
grantedAuthorityMappings {
   Admin {
      grantedAuthorities = [ "RunQuery","CancelQuery"]
   }

   Viewer {
      grantedAuthorities = [ "BrowseCatalog" ]
   }
}
----
////

{short-product-name} roles and corresponding authorities can be found below:

|===
| Role | Granted Authorities

| Admin
| Everything

| Viewer
| BrowseSchema

| MetricsViewer
| ViewMetrics, +
BrowseSchema

| QueryRunner
| RunQuery

| PlatformManager
| CancelQuery, +
ViewQueryHistory +
ViewHistoricQueryResults +
BrowseSchema +
EditSchema +
ViewCaskDefinitions +
EditCaskDefinitions +
ViewPipelines +
EditPipelines +
ViewAuthenticationTokens +
EditAuthenticationTokens +
ViewConnections +
EditConnections
|===

[#permissions]
== Permissions

To perform an activity, users must be associated with a role that grants the related authority.

// Permission → endpoint mapping can be found in detail here: https://hazelcast.atlassian.net/browse/HZX-10?focusedCommentId=102270
|===
| Activity | Required permission

| Issue a query through the UI
| RunQuery

| Issue a query through the API
| RunQuery

| Cancel a running query
| CancelQuery

| Browse the query history in the UI
| ViewQueryHistory

| View the results of historic queries
| ViewHistoricQueryResults

| Browse the data catalog
| BrowseCatalog

| View the registered schemas
| BrowseSchema

| Modify a catalog entry
| EditSchema

| Import a new schema through the schema importer UI
| EditSchema

| List pipelines
| ViewPipelines

| Add a new pipeline
| EditPipelines

| Edit an existing pipeline
| EditPipelines

| View authentication tokens {short-product-name} uses in requests
| ViewAuthenticationTokens

| Edit authentication tokens {short-product-name} uses in requests
| EditAuthenticationTokens

| View configured data sources
| ViewConnections

| Edit configured data sources
| EditConnections
|===

== Assign users to roles

Since authentication is done via MC, users must already have https://docs.hazelcast.com/management-center/latest/deploy-manage/user-management#user-roles[MC roles] assigned.
Once a user has a valid MC role, the user will have the corresponding role in {short-product-name}.
The role mapping can be found <<role-mapping,here>>.

If a user does not have any roles in MC, they will not have a corresponding role in {short-product-name}, meaning a logged-in user will not be able to do anything and will see a blank navigation bar.

[#role-mapping]
== Role mapping between MC and {short-product-name}

The mapping:

* Admin → Admin
* User → PlatformManager + QueryRunner + Viewer
* Read-Only User → Viewer
* Metrics-Only User → Viewer + MetricsViewer

Example: If a user has `User` role in MC, they will have `PlatformManager`, `QueryRunner` and `Viewer` roles in {short-product-name}.
