= Manage secrets
:description: Learn how to store sensitive data.

Generally, when defining either xref:describe-data-sources:configure-connections.adoc[connections] or xref:describe-data-sources:authentication-to-services.adoc[authentication tokens]
you need to store sensitive values.

As {short-product-name} is built around file-based and Git-based data stores, these are values you generally don't want checked in.

== Environment variables

All {short-product-name} config files are defined in https://github.com/lightbend/config#examples-of-hocon[HOCON] format, which allows for variable https://github.com/lightbend/config/blob/main/HOCON.md#substitutions[substitution] from the https://github.com/lightbend/config/blob/main/HOCON.md#substitution-fallback-to-environment-variables[environment].

When deploying {short-product-name} into production, it's recommended to keep secrets in a secret store (e.g., https://www.vaultproject.io/[Vault]), and inject
them into the environment as part of the machine provisioning process.

{short-product-name} will correctly inject these values into placeholders.

== Use env.conf for sensitive data

In addition to the standard HOCON rules for resolving variables, {short-product-name} supports
the use of an `env.conf` file as a source for substitutions.

This can be useful when developing locally, to ensure that sensitive values aren't accidentally
checked in, but to avoid having to configure environment variables, which can be fiddly.

The general workflow is as follows:

* Define a `connections.conf` file with your connections, using `+${variables}+` for placeholders of sensitive data
* Create a local `env.conf` file
* The location of the `env.conf` file must be alongside the `connections.conf` file i.e., the path defined in your taxi.conf file
* Populate the env.conf file with sensitive values

For example:
```hocon connections.conf
 jdbc { 
    my-connection {
         // ... other params omitted for brevity ... 
         connectionParams { 
            password = ${postgres_password} // Reads the environment variable "postgres_password" 
        } 
    } 
}
``` 

```hocon env.conf 
postgres_password=hello123
```
